name: maneja_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^32.1.23
  image: ^4.2.0
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.2
  url_launcher: ^6.2.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/ManejarUY_logo.png
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/ManejarUY_logo.png
  android_gravity: center

  android_12:
    color: "#FFFFFF"
    image: assets/images/ManejarUY_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/pdf/guia_nacional_conduccion.pdf
    - assets/senales_reglamentarias/
    - assets/senales_preventivas/
    - assets/senales_manuales/
    - assets/images/patron_fondo.png
    - assets/images/ManejarUY_logo.png
